// <auto-generated />
using System;
using GBPColmadoNet.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBPColmadoNet.Data.Migrations
{
    [DbContext(typeof(ColmadoContext))]
    [Migration("20260506213346_AgregarDevolucion")]
    partial class AgregarDevolucion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Abono", b =>
                {
                    b.Property<int>("AbonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonoId"));

                    b.Property<int>("CuentaPorCobrarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AbonoId")
                        .HasName("PK__Abonos__0038E98AC6D30B76");

                    b.HasIndex("CuentaPorCobrarId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Abonos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Bitacora__3214EC07FC14A725");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Bitacora", (string)null);
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CarritoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaItbis")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarritoItems");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__F353C1E518F5D3D0");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CierresCaja", b =>
                {
                    b.Property<int>("CierreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CierreId"));

                    b.Property<decimal?>("AbonosRecibidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Diferencia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("([MontoRealEntregado]-[MontoFinalEsperado])", false);

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Abierto");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime");

                    b.Property<decimal>("MontoFinalEsperado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MontoRealEntregado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VentasCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("VentasEfectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("CierreId")
                        .HasName("PK__CierresC__0BAD3FBAAC6E5689");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CierresCaja", (string)null);
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId")
                        .HasName("PK__Clientes__71ABD0878150900E");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraId"));

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalItbis")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TotalITBIS");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CompraId")
                        .HasName("PK__Compras__067DA7457376CA34");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.ComprasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId")
                        .HasName("PK__ComprasD__6E19D6DAE8AE5771");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ComprasDetalle", (string)null);
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.ConfiguracionesNegocio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CiudadProvincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImpresoraPredeterminada")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ItbisDefecto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MargenGananciaDefecto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MensajeTicket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rnc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RNC");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesNegocio", (string)null);
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CuentasPorCobrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BalancePendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("DiasCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("MontoAbonado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MontoDeuda")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CuentasP__3214EC072332A8FD");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VentaId");

                    b.ToTable("CuentasPorCobrar", (string)null);
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Devolucion", b =>
                {
                    b.Property<int>("DevolucionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevolucionId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("MontoReembolsado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("DevolucionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 3)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TasaItbis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(18.00m)
                        .HasColumnName("TasaITBIS");

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A430AEA3DB3AD134");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex(new[] { "CodigoBarras" }, "UQ__Producto__F61589C8C52A37C0")
                        .IsUnique()
                        .HasFilter("[CodigoBarras] IS NOT NULL");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Proveedore", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rnc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RNC");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProveedorId")
                        .HasName("PK__Proveedo__61266A59C49B9362");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK__Roles__F92302F1540796D8");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Roles__75E3EFCF25872476")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE7B8D62F41B4");

                    b.HasIndex(new[] { "Username" }, "UQ__Usuarios__536C85E4B6AD73C9")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TotalItbis")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TotalITBIS");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("VentaId")
                        .HasName("PK__Ventas__5B4150AC39DD5EC8");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.VentasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId")
                        .HasName("PK__VentasDe__6E19D6DA816C1A49");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentasDetalle", (string)null);
                });

            modelBuilder.Entity("UsuarioRole", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("PK__UsuarioR__24AFD7977837963E");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Abono", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.CuentasPorCobrar", "CuentaPorCobrar")
                        .WithMany("Abonos")
                        .HasForeignKey("CuentaPorCobrarId")
                        .IsRequired()
                        .HasConstraintName("FK__Abonos__CuentaPo__19DFD96B");

                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "Usuario")
                        .WithMany("Abonos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Abonos__UsuarioI__1AD3FDA4");

                    b.Navigation("CuentaPorCobrar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Bitacora", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "Usuario")
                        .WithMany("Bitacoras")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Bitacora__Usuari__25518C17");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CierresCaja", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "Usuario")
                        .WithMany("CierresCajas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__CierresCa__Usuar__2180FB33");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Compra", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Proveedore", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK__Compras__Proveed__10566F31");

                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Compras__Usuario__114A936A");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.ComprasDetalle", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Compra", "Compra")
                        .WithMany("ComprasDetalles")
                        .HasForeignKey("CompraId")
                        .IsRequired()
                        .HasConstraintName("FK__ComprasDe__Compr__14270015");

                    b.HasOne("GBPColmadoNet.Data.Models.Producto", "Producto")
                        .WithMany("ComprasDetalles")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__ComprasDe__Produ__151B244E");

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CuentasPorCobrar", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Cliente", "Cliente")
                        .WithMany("CuentasPorCobrars")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__CuentasPo__Clien__0A9D95DB");

                    b.HasOne("GBPColmadoNet.Data.Models.Venta", "Venta")
                        .WithMany("CuentasPorCobrars")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK__CuentasPo__Venta__0B91BA14");

                    b.Navigation("Cliente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Devolucion", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Devolucio__Usuar");

                    b.HasOne("GBPColmadoNet.Data.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .IsRequired()
                        .HasConstraintName("FK__Devolucio__Venta");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Producto", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__Productos__Categ__5629CD9C");

                    b.HasOne("GBPColmadoNet.Data.Models.Proveedore", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("FK__Productos__Prove__571DF1D5");

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Venta", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Cliente", "Cliente")
                        .WithMany("Venta")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK__Ventas__ClienteI__5FB337D6");

                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "Usuario")
                        .WithMany("Venta")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Ventas__UsuarioI__5EBF139D");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.VentasDetalle", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Producto", "Producto")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__VentasDet__Produ__6383C8BA");

                    b.HasOne("GBPColmadoNet.Data.Models.Venta", "Venta")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK__VentasDet__Venta__628FA481");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("UsuarioRole", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioRo__RolId__2DE6D218");

                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioRo__Usuar__2CF2ADDF");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Cliente", b =>
                {
                    b.Navigation("CuentasPorCobrars");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Compra", b =>
                {
                    b.Navigation("ComprasDetalles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CuentasPorCobrar", b =>
                {
                    b.Navigation("Abonos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Producto", b =>
                {
                    b.Navigation("ComprasDetalles");

                    b.Navigation("VentasDetalles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Proveedore", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Usuario", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Bitacoras");

                    b.Navigation("CierresCajas");

                    b.Navigation("Compras");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Venta", b =>
                {
                    b.Navigation("CuentasPorCobrars");

                    b.Navigation("VentasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
