// <auto-generated />
using System;
using GBPColmadoNet.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBPColmadoNet.Data.Migrations
{
    [DbContext(typeof(ColmadoContext))]
    [Migration("20260509_172112_AgregarPermisos")]
    partial class AgregarPermisos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Abono", b =>
                {
                    b.Property<int>("AbonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AbonoId");

                    b.Property<decimal?>("Abono1")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Abono");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("AbonoId")
                        .HasName("PK__Abonos__F29073FCBBCE5447");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Abonos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Bitacora", b =>
                {
                    b.Property<int>("BitacoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BitacoraId");

                    b.Property<string>("Accion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Accion");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha");

                    b.Property<string>("Tabla")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Tabla");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("BitacoraId")
                        .HasName("PK__Bitacora__81EC9E8A6F5FDE7F");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Bitacora");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__D46D04320A3A6C79");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CierresCaja", b =>
                {
                    b.Property<int>("CierreCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CierreCajaId");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Diferencia");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCierre");

                    b.Property<decimal?>("MontoCierre")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoCierre");

                    b.Property<decimal?>("MontoSistema")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoSistema");

                    b.Property<int>("UsuarioCierreId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioCierreId");

                    b.HasKey("CierreCajaId")
                        .HasName("PK__CierresC__6B4C3A8B1C3A80E5");

                    b.HasIndex("UsuarioCierreId");

                    b.ToTable("CierresCajas");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Apellido");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Cedula");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Correo");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("ClienteId")
                        .HasName("PK__Clientes__A2D299Z1Y7F60B89");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompraId");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("ProveedorId");

                    b.Property<decimal?>("TotalItbis")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalItbis");

                    b.Property<decimal?>("TotalNeto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalNeto");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("CompraId")
                        .HasName("PK__Compras__C6D3A2B08E91F8B4");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.ComprasDetalle", b =>
                {
                    b.Property<int>("ComprasDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComprasDetalleId");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("CompraId")
                        .HasColumnType("int")
                        .HasColumnName("CompraId");

                    b.Property<decimal?>("Itbis")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Itbis");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoId");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SubTotal");

                    b.HasKey("ComprasDetalleId")
                        .HasName("PK__ComprasDe__9DB07B2B5F0BDEFC");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ComprasDetalles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.ConfiguracionesNegocio", b =>
                {
                    b.Property<int>("ConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfiguracionId");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Moneda")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Moneda");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NombreComercial");

                    b.Property<decimal?>("PorcentajeItbis")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PorcentajeItbis");

                    b.Property<string>("RNC")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RNC");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("ConfiguracionId")
                        .HasName("PK__Configur__EDE4D1C84F51B");

                    b.ToTable("ConfiguracionesNegocios");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CuentasPorCobrar", b =>
                {
                    b.Property<int>("CuentaPorCobrarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CuentaPorCobrarId");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha");

                    b.Property<decimal?>("MontoAbonado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoAbonado");

                    b.Property<decimal?>("MontoDeuda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoDeuda");

                    b.Property<int?>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("VentaId");

                    b.HasKey("CuentaPorCobrarId")
                        .HasName("PK__CuentasP__CF6DCBA8E6EC96D3");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VentaId");

                    b.ToTable("CuentasPorCobrars");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Devolucion", b =>
                {
                    b.Property<int>("DevolucionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DevolucionId");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("IdVenta");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Tipo");

                    b.HasKey("DevolucionId")
                        .HasName("PK__Devolucio__ID");

                    b.HasIndex("IdVenta");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PermisoId");

                    b.Property<string>("Accion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Accion");

                    b.Property<bool>("Permite")
                        .HasColumnType("bit")
                        .HasColumnName("Permite");

                    b.Property<string>("Modulo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Modulo");

                    b.Property<int?>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.HasKey("PermisoId")
                        .HasName("PK__Permisos__A16D1EC041379BA5");

                    b.HasIndex(new[] { "RolId", "Modulo", "Accion" }, "IX_Permiso_rol_modulo_accion")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoId");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Categoria");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CodigoBarras");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<decimal?>("PrecioCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioCompra");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioVenta");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UnidadMedida");

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A30BD8B87CC23F");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Proveedore", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProveedorId");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Correo");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("RNC")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RNC");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("ProveedorId")
                        .HasName("PK__Proveedo__60F7F5D71B9CBEFB");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("RolId")
                        .HasName("PK__Roles__F92302F1540796D8");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[Nombre] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Rol")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE7B8D62F41B4");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VentaId");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha");

                    b.Property<decimal?>("TotalItbis")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalItbis");

                    b.Property<decimal?>("TotalNeto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalNeto");

                    b.Property<string>("TipoPago")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TipoPago");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("VentaId")
                        .HasName("PK__Ventas__5B4150AC39DD5EC8");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.VentasDetalle", b =>
                {
                    b.Property<int>("VentasDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VentasDetalleId");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<decimal?>("Itbis")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Itbis");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoId");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SubTotal");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("VentaId");

                    b.HasKey("VentasDetalleId")
                        .HasName("PK__VentasDe__4B711D4D912");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentasDetalles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CarritoItem", b =>
                {
                    b.Property<int>("CarritoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CarritoItemId");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoId");

                    b.HasKey("CarritoItemId")
                        .HasName("PK__CarritoI__E");

                    b.ToTable("CarritoItems");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Abono", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Cliente", null)
                        .WithMany("Abonos")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK__Abonos__ClienteId__01");

                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", null)
                        .WithMany("Abonos")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Abonos__UsuarioId__02");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Bitacora", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", null)
                        .WithMany("Bitacoras")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Bitacora__UsuarioId__03");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CierresCaja", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "UsuarioCierre")
                        .WithMany("CierresCajas")
                        .HasForeignKey("UsuarioCierreId")
                        .HasConstraintName("FK__CierresC__Usuario__04")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Compra", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Proveedore", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("FK__Compras__Proveedor__05");

                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Compras__Usuario__06");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.ComprasDetalle", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Compra", "Compra")
                        .WithMany("ComprasDetalles")
                        .HasForeignKey("CompraId")
                        .HasConstraintName("FK__ComprasDe__CompraId__07")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBPColmadoNet.Data.Models.Producto", "Producto")
                        .WithMany("ComprasDetalles")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__ComprasDe__Producto__08")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.CuentasPorCobrar", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Cliente", "Cliente")
                        .WithMany("CuentasPorCobrars")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK__CuentasP__Client__09")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBPColmadoNet.Data.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK__CuentasP__Venta__10");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Devolucion", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Venta", null)
                        .WithMany("Devoluciones")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("FK__Devolucio__IdVen__11");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Permiso", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Role", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK__Permisos__RolId__12")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Producto", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__Producto__Categ__13");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Venta", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK__Ventas__ClienteId__14");

                    b.HasOne("GBPColmadoNet.Data.Models.Usuario", "Usuario")
                        .WithMany("Venta")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Ventas__UsuarioId__15");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.VentasDetalle", b =>
                {
                    b.HasOne("GBPColmadoNet.Data.Models.Producto", "Producto")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__VentasDe__Produ__16")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBPColmadoNet.Data.Models.Venta", "Venta")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK__VentasDe__VentaId__17")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Venta", b =>
                {
                    b.Navigation("Devoluciones");

                    b.Navigation("VentasDetalles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Cliente", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("CuentasPorCobrars");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Compra", b =>
                {
                    b.Navigation("ComprasDetalles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Producto", b =>
                {
                    b.Navigation("ComprasDetalles");

                    b.Navigation("VentasDetalles");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Proveedore", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Role", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("GBPColmadoNet.Data.Models.Usuario", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Bitacoras");

                    b.Navigation("CierresCajas");

                    b.Navigation("Compras");

                    b.Navigation("Venta");
                });
#pragma warning restore 612, 618
        }
    }
}